// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkyHelp.Context;

#nullable disable

namespace SkyHelp.Migrations
{
    [DbContext(typeof(SkyHelpContext))]
    [Migration("20260818144921_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SkyHelp.Domiciliarios", b =>
                {
                    b.Property<Guid>("IdDomiciliario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EstadoActividad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("IDUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PlacaVehiculo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdDomiciliario");

                    b.HasIndex("IDUsuario");

                    b.ToTable("Domiciliarios", (string)null);
                });

            modelBuilder.Entity("SkyHelp.Estadisticas", b =>
                {
                    b.Property<Guid>("IdEstadistica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Datos")
                        .IsRequired()
                        .HasColumnType("ntext");

                    b.Property<bool>("ExportadoExcel")
                        .HasColumnType("bit");

                    b.Property<bool>("ExportadoPDF")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TipoGrafico")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdEstadistica");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Estadisticas", (string)null);
                });

            modelBuilder.Entity("SkyHelp.ExportacionesEstadisticas", b =>
                {
                    b.Property<Guid>("IdExportado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExportadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaExportacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Formato")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("IdEstadistica")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdExportado");

                    b.HasIndex("IdEstadistica");

                    b.ToTable("ExportacionesEstadisticas", (string)null);
                });

            modelBuilder.Entity("SkyHelp.Models.Articulos", b =>
                {
                    b.Property<Guid>("IdArticulo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CalificacionPromedio")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TotalVistas")
                        .HasColumnType("int");

                    b.HasKey("IdArticulo");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Articulos", (string)null);
                });

            modelBuilder.Entity("SkyHelp.Models.Auditoria", b =>
                {
                    b.Property<Guid>("IDLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaEvento")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IDRegistro")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TablaAfectada")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IDLog");

                    b.HasIndex("IDUsuario");

                    b.ToTable("Auditoria", (string)null);
                });

            modelBuilder.Entity("SkyHelp.Models.EstadosTicket", b =>
                {
                    b.Property<Guid>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NombreEstado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdEstado");

                    b.ToTable("EstadosTickets", (string)null);
                });

            modelBuilder.Entity("SkyHelp.Models.Evaluaciones", b =>
                {
                    b.Property<Guid>("IdEvaluacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Calificacion")
                        .HasColumnType("int");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaEvaluacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdTicket")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdEvaluacion");

                    b.HasIndex("IdTicket");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Evaluaciones", (string)null);
                });

            modelBuilder.Entity("SkyHelp.Models.Reportes", b =>
                {
                    b.Property<Guid>("IdReporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdOrigen")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OrigenTabla")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TipoReporte")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdReporte");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Reportes", (string)null);
                });

            modelBuilder.Entity("SkyHelp.Models.Roles", b =>
                {
                    b.Property<Guid>("IDRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IDRol");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("SkyHelp.Models.Tickets", b =>
                {
                    b.Property<Guid>("IdTicket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("IdDomiciliario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdEstado")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdTecnico")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NumeroTicket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NumeroTicket"));

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdTicket");

                    b.HasIndex("IdDomiciliario");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdTecnico");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Tickets", (string)null);
                });

            modelBuilder.Entity("SkyHelp.Models.Usuarios", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EstadoCuenta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("IdRol")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreUsuarios")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdRol");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("SkyHelp.Notificaciones", b =>
                {
                    b.Property<Guid>("IdNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IDTicket")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Leido")
                        .HasColumnType("bit");

                    b.Property<string>("MedioEnvio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdNotificacion");

                    b.HasIndex("IDTicket");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Notificaciones", (string)null);
                });

            modelBuilder.Entity("SkyHelp.Pedidos", b =>
                {
                    b.Property<Guid>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DireccionEntrega")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EstadoPedido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaPedido")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdDomiciliario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdPedido");

                    b.HasIndex("IdDomiciliario");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Pedidos", (string)null);
                });

            modelBuilder.Entity("SkyHelp.Tecnicos", b =>
                {
                    b.Property<Guid>("IdTecnico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdTecnico");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Tecnicos", (string)null);
                });

            modelBuilder.Entity("SkyHelp.Domiciliarios", b =>
                {
                    b.HasOne("SkyHelp.Models.Usuarios", "Usuario")
                        .WithMany("Domiciliarios")
                        .HasForeignKey("IDUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SkyHelp.Estadisticas", b =>
                {
                    b.HasOne("SkyHelp.Models.Usuarios", "Usuario")
                        .WithMany("Estadisticas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SkyHelp.ExportacionesEstadisticas", b =>
                {
                    b.HasOne("SkyHelp.Estadisticas", "Estadistica")
                        .WithMany("ExportacionesEstadisticas")
                        .HasForeignKey("IdEstadistica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estadistica");
                });

            modelBuilder.Entity("SkyHelp.Models.Articulos", b =>
                {
                    b.HasOne("SkyHelp.Models.Usuarios", "Usuario")
                        .WithMany("Articulos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SkyHelp.Models.Auditoria", b =>
                {
                    b.HasOne("SkyHelp.Models.Usuarios", "Usuario")
                        .WithMany("Auditorias")
                        .HasForeignKey("IDUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SkyHelp.Models.Evaluaciones", b =>
                {
                    b.HasOne("SkyHelp.Models.Tickets", "Ticket")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("IdTicket")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkyHelp.Models.Usuarios", "Usuario")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SkyHelp.Models.Reportes", b =>
                {
                    b.HasOne("SkyHelp.Models.Usuarios", "Usuario")
                        .WithMany("Reportes")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SkyHelp.Models.Tickets", b =>
                {
                    b.HasOne("SkyHelp.Domiciliarios", "Domiciliario")
                        .WithMany("Tickets")
                        .HasForeignKey("IdDomiciliario");

                    b.HasOne("SkyHelp.Models.EstadosTicket", "EstadoTicket")
                        .WithMany("Tickets")
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkyHelp.Tecnicos", "Tecnico")
                        .WithMany("Tickets")
                        .HasForeignKey("IdTecnico");

                    b.HasOne("SkyHelp.Models.Usuarios", "Usuario")
                        .WithMany("Tickets")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domiciliario");

                    b.Navigation("EstadoTicket");

                    b.Navigation("Tecnico");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SkyHelp.Models.Usuarios", b =>
                {
                    b.HasOne("SkyHelp.Models.Roles", "Rol")
                        .WithMany("Usuario")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SkyHelp.Notificaciones", b =>
                {
                    b.HasOne("SkyHelp.Models.Tickets", "Ticket")
                        .WithMany()
                        .HasForeignKey("IDTicket")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkyHelp.Models.Usuarios", "Usuario")
                        .WithMany("Notificaciones")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SkyHelp.Pedidos", b =>
                {
                    b.HasOne("SkyHelp.Domiciliarios", "Domiciliario")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdDomiciliario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkyHelp.Models.Usuarios", "Usuario")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domiciliario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SkyHelp.Tecnicos", b =>
                {
                    b.HasOne("SkyHelp.Models.Usuarios", "Usuario")
                        .WithMany("Tecnico")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SkyHelp.Domiciliarios", b =>
                {
                    b.Navigation("Pedidos");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("SkyHelp.Estadisticas", b =>
                {
                    b.Navigation("ExportacionesEstadisticas");
                });

            modelBuilder.Entity("SkyHelp.Models.EstadosTicket", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("SkyHelp.Models.Roles", b =>
                {
                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SkyHelp.Models.Tickets", b =>
                {
                    b.Navigation("Evaluaciones");
                });

            modelBuilder.Entity("SkyHelp.Models.Usuarios", b =>
                {
                    b.Navigation("Articulos");

                    b.Navigation("Auditorias");

                    b.Navigation("Domiciliarios");

                    b.Navigation("Estadisticas");

                    b.Navigation("Evaluaciones");

                    b.Navigation("Notificaciones");

                    b.Navigation("Pedidos");

                    b.Navigation("Reportes");

                    b.Navigation("Tecnico");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("SkyHelp.Tecnicos", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
